"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.PLUGIN_PAGES_UPDATE = exports.PLUGIN_CONTAINERS_UPDATE = exports.PLUGIN_COMPONENTS_UPDATE = void 0;
var PLUGIN_COMPONENTS_UPDATE = 'PLUGIN_COMPONENTS_UPDATE';
exports.PLUGIN_COMPONENTS_UPDATE = PLUGIN_COMPONENTS_UPDATE;
var PLUGIN_CONTAINERS_UPDATE = 'PLUGIN_CONTAINERS_UPDATE';
exports.PLUGIN_CONTAINERS_UPDATE = PLUGIN_CONTAINERS_UPDATE;
var PLUGIN_PAGES_UPDATE = 'PLUGIN_PAGES_UPDATE';
exports.PLUGIN_PAGES_UPDATE = PLUGIN_PAGES_UPDATE;